### ISSUE TITLE
Zoom amount doesn't actually works

### ISSUE THREAD

**Issue by abhishek-quck** [samjonesigd/vue-image-zoomer#30]
installing the vue-image-zoomer^2.4.0 setting it all up goes good and all but doen't actually zooms out instead if focuses on the right side of the image. No matter how much zoom amount you set and no matter what position you start to hover on it.
what's the matter exactly can you confirm ?

**Comment by samjonesigd** [comment]
Can you put your code on codepen or something? @abhishek-quck

**Comment by ZawHlaingWin007** [comment]
Same here! When hover on image, it shows right bottom corner of image with white screen.

**Comment by samjonesigd** [comment]
@ZawHlaingWin007 @abhishek-quck Can you share your code,  I set up a quick demo here and it is working as it should on the latest version? 

https://codesandbox.io/p/devbox/agitated-tharp-jwhzgk?file=%2Fsrc%2FApp.vue%3A16%2C49

**Comment by yoshi29** [comment]
@samjonesigd This happens to me as well. I use zoomer with vue 3, composition api, and primevue. I can share my code with you later.

**Comment by yoshi29** [comment]
@samjonesigd It seems this issue is related to the use of tailwind. You can check my code here:
https://codesandbox.io/p/github/yoshi29/vue-image-zoomer-issue/main?file=%2Fvite.config.ts

**Comment by samjonesigd** [comment]
Thank you for providing an example, looks like this that tailwind sets on images, will look at overriding it. You will be able to override with custom css for a quick fix now

```css
    max-width: 100%;
```

to override set zoom to `max-width:none` on `vh--image` class

**Comment by mx91213115** [comment]
If the image is white or not in the right position, use this. I spent an afternoon trying it out.
`.vh--image {
	max-width: none;
}
.vh--outer {
	picture {
		position: static;
	}
}`

**Comment by samjonesigd** [comment]
Fixed, sorry it took a while #36

**Comment by Ischafak** [comment]
i still have the same problem btw

if i give 

<VueImageZoomer
      :regular="formData.image"
      :zoom="formData.image"
      :zoom-amount="30"

      alt="Sky"
      :show-message="false"
      @on-zoom="zoom = true"
      @off-zoom="zoom = false"
    />

regular and zoom together it works but if i give regular alone its not working

**Comment by samjonesigd** [comment]
@Ischafak probably a different bug, if you open an issue ill take a look when i can
